"""
Sindlish Language Interpreter — CLI Entry Point.

Provides a command-line interface for the Sindlish programming language,
allowing users to run files, start an interactive REPL, evaluate code strings,
and inspect the internal representation (tokens, AST) for debugging purposes.
"""

import argparse
import os
import sys
import time
from pathlib import Path

from . import get_version
from .errors import SindhiBaseError

VERSION = get_version()


def _read_file(file_path: str) -> str:
    """Read a Sindlish (.sd) source file with a UTF-8 BOM-tolerant encoding."""
    with open(file_path, "r", encoding="utf-8-sig") as f:
        return f.read()


def run_tokens(code: str):
    """Print the tokens generated by the lexer."""
    from .frontend.lexer import Lexer

    try:
        lexer = Lexer(code)
        tokens = lexer.generate_tokens()
        for token in tokens:
            print(token)
    except SindhiBaseError as e:
        print(f"Lexer Error: {e}")
        sys.exit(1)


def run_ast(code: str):
    """Print the Abstract Syntax Tree generated by the parser."""
    from .frontend.ast_formatter import print_ast
    from .frontend.lexer import Lexer
    from .frontend.parser import Parser

    try:
        lexer = Lexer(code)
        tokens = lexer.generate_tokens()
        parser = Parser(tokens, code)
        ast = parser.parse()
        print_ast(ast)
    except SindhiBaseError as e:
        print(f"Parser Error: {e}")
        sys.exit(1)


def run_file(file_path: str, show_time: bool = False):
    """Execute a Sindlish (.sd) file."""
    from . import Interpreter

    if not file_path.endswith(".sd"):
        print(f"Error: File '{file_path}' must have .sd extension.")
        sys.exit(1)

    if not os.path.exists(file_path):
        print(f"Error: File '{file_path}' not found.")
        sys.exit(1)

    try:
        code = _read_file(file_path)
    except (OSError, UnicodeError) as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

    interp = Interpreter()

    start = time.perf_counter()
    interp.run_source(code)
    end = time.perf_counter()

    if show_time:
        print(f"\n[Execution time: {end - start:.4f}s]")


def run_eval(code: str, show_time: bool = False):
    """Evaluate a string of Sindlish code."""
    from . import Interpreter

    interp = Interpreter()
    start = time.perf_counter()
    interp.run_source(code)
    end = time.perf_counter()

    if show_time:
        print(f"\n[Execution time: {end - start:.4f}s]")


def check_file(file_path: str):
    """Check a file for syntax and resolution errors without executing it."""
    from . import Interpreter

    if not os.path.exists(file_path):
        print(f"Error: File '{file_path}' not found.")
        sys.exit(1)

    try:
        code = _read_file(file_path)
        Interpreter().check(code)
        print(f"OK: '{file_path}' passed syntax and semantic check.")
    except SindhiBaseError as e:
        print(f"Check Failed: {e}")
        sys.exit(1)


def show_docs():
    """Display the offline documentation."""
    import pydoc

    docs_path = _docs_path()
    if not docs_path.exists():
        print("Error: Offline documentation file not found.")
        sys.exit(1)

    try:
        with open(docs_path, "r", encoding="utf-8-sig") as f:
            docs_content = f.read()
        pydoc.pager(docs_content)
    except (OSError, UnicodeError) as e:
        print(f"Error reading documentation: {e}")
        sys.exit(1)


def _docs_path() -> Path:
    """
    Locate offline_docs.txt.

    Order: PyInstaller bundle (sys._MEIPASS) → installed package → source tree.
    """
    if getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS"):
        meipass = Path(sys._MEIPASS) / "offline_docs.txt"
        if meipass.exists():
            return meipass
    package_path = Path(__file__).parent / "offline_docs.txt"
    if package_path.exists():
        return package_path
    return Path(__file__).resolve().parents[1] / "offline_docs.txt"


def main():
    parser = argparse.ArgumentParser(
        prog="sindlish",
        description="Sindlish Language Interpreter - A localized high-level programming language.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  sindlish run script.sd       # Run a file
  sindlish repl                # Start interactive shell
  sindlish eval "likh(1+2)"    # Evaluate code directly
  sindlish tokens script.sd    # View lexer tokens
  sindlish ast script.sd       # View parser AST
""",
    )

    parser.add_argument(
        "-v", "--version", action="version", version=f"Sindlish Interpreter {VERSION}"
    )

    subparsers = parser.add_subparsers(dest="command", help="Commands")

    # Run command
    run_parser = subparsers.add_parser("run", help="Run a Sindlish (.sd) file")
    run_parser.add_argument("file", help="Path to the .sd file")
    run_parser.add_argument(
        "-t", "--time", action="store_true", help="Show execution time"
    )

    # REPL command
    subparsers.add_parser("repl", help="Start the interactive REPL")

    # Eval command
    eval_parser = subparsers.add_parser("eval", help="Evaluate Sindlish code string")
    eval_parser.add_argument("code", help="Sindlish code to evaluate")
    eval_parser.add_argument(
        "-t", "--time", action="store_true", help="Show execution time"
    )

    # Tokens command
    tokens_parser = subparsers.add_parser("tokens", help="Show tokens for a file")
    tokens_parser.add_argument("file", help="Path to the .sd file")

    # AST command
    ast_parser = subparsers.add_parser("ast", help="Show AST for a file")
    ast_parser.add_argument("file", help="Path to the .sd file")

    # Check command
    check_parser = subparsers.add_parser("check", help="Check file for syntax errors")
    check_parser.add_argument("file", help="Path to the .sd file")

    # Docs command
    subparsers.add_parser("docs", help="View offline documentation")

    # Handle legacy behavior and defaults
    if len(sys.argv) == 1:
        # No arguments: start REPL
        _start_repl()
        return

    # If first arg is a file ending in .sd, assume 'run'
    if not sys.argv[1].startswith("-") and sys.argv[1] not in subparsers.choices and sys.argv[1].endswith(".sd"):
        sys.argv.insert(1, "run")

    args = parser.parse_args()

    if args.command == "run":
        run_file(args.file, args.time)
    elif args.command == "repl":
        _start_repl()
    elif args.command == "eval":
        run_eval(args.code, args.time)
    elif args.command == "tokens":
        if not os.path.exists(args.file):
            print(f"Error: File '{args.file}' not found.")
            sys.exit(1)
        run_tokens(_read_file(args.file))
    elif args.command == "ast":
        if not os.path.exists(args.file):
            print(f"Error: File '{args.file}' not found.")
            sys.exit(1)
        run_ast(_read_file(args.file))
    elif args.command == "check":
        check_file(args.file)
    elif args.command == "docs":
        show_docs()
    else:
        # If somehow we get here without a command, start REPL
        _start_repl()


def _start_repl():
    from .repl import start_repl

    start_repl(VERSION)


if __name__ == "__main__":
    main()